 
package pkgfinal.project;

public class Searching extends javax.swing.JFrame {


    public Searching() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BF = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        pattern1 = new javax.swing.JTextField();
        Output1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        text2 = new javax.swing.JTextField();
        pattern2 = new javax.swing.JTextField();
        Output2 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        KMP = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("String Matcing");
        setName("searching"); // NOI18N

        BF.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        BF.setText("Brute Force");

        text1.setText("Enter Text");
        text1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text1MouseClicked(evt);
            }
        });

        pattern1.setText("Enter Pattern");
        pattern1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pattern1MouseClicked(evt);
            }
        });

        Output1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Output1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Output1.setText("Output");

        btn1.setLabel("Match");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        text2.setText("Enter Text");
        text2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text2MouseClicked(evt);
            }
        });

        pattern2.setText("Enter Pattern");
        pattern2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pattern2MouseClicked(evt);
            }
        });

        Output2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Output2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Output2.setText("Output");

        btn2.setText("Match");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        KMP.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        KMP.setText("KMP");

        Title.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        Title.setText("String Matching Algorithm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pattern1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Output1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BF, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                        .addComponent(KMP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pattern2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Output2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KMP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pattern2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pattern1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Output2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Output1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(295, 295, 295))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn2)
                            .addComponent(btn1))
                        .addGap(18, 18, 18)
                        .addComponent(exit)
                        .addGap(182, 182, 182))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text1MouseClicked
        Output1.setText("Output");                          // Reset output labe when click on Text textfield...  
        text1.setText("");                                  // Reset Text textfield when click on Text textfield...
    }//GEN-LAST:event_text1MouseClicked

    private void pattern1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pattern1MouseClicked
       Output1.setText("Output");                           // Reset output labe when click on pattern textfield...
        pattern1.setText("");                               // Reset pattern textfield when click on pattern textfield...
    }//GEN-LAST:event_pattern1MouseClicked

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
                                                                        // For Brute Force Check Matching ...
                                                                       
        String text,pattern;
        
        text=text1.getText();
        pattern=pattern1.getText();
        int n=text.length();
        int m=pattern.length();
        int i=0,j=0,k=0,count=0;
        boolean found=false;
        while(i<n)                                       // To visit every character of Text...
        {
            k=i;
            while(j<m&&k<n)                              // To Match Substring...
            {
       //         System.out.println(" k ="+k);
                
                if(text.charAt(k)==pattern.charAt(j))   // compare text and pattern character by character 
                {
         //           System.out.println(" j "+j);
                    count++;
                    j++;
                    k++;
                }
                else
                {
                    break;
                }           
            }
            
            if(count==m)
             {
                found=true;          // if substirng found then break
                break;
            }
            count=0;
            j=0;    
            i++;
        }
        if(found)
        {
            Output1.setText("Pattern Matched at index "+i);
        }
        else
        {
            Output1.setText("Pattern Not Matched !!!");
    }
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
       
    }//GEN-LAST:event_exitActionPerformed

    private void text2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text2MouseClicked
        Output2.setText("Output");
        text2.setText("");
    }//GEN-LAST:event_text2MouseClicked

    private void pattern2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pattern2MouseClicked
        Output2.setText("Output");
        pattern2.setText("");
    }//GEN-LAST:event_pattern2MouseClicked

    
    static int KMP(String patten, String txt)
    {
        int patten_length = patten.length();
        int txt_length = txt.length();
 
        int array[] = new int[patten_length];
        int j = 0;  
 
        makearray(patten,patten_length,array);
        boolean found=false;
        int i = 0,ans=-1;  
        while (i < txt_length)
        {
            if (patten.charAt(j) == txt.charAt(i))
            {
                j++;
                i++;
            }
            if (j == patten_length)
            {
             
            //    System.out.println("Found pattern "+"at index " + (i-j));
                
                 ans=i-j;
                j = array[j-1];
                break;
            }
            else if (i < txt_length && patten.charAt(j) != txt.charAt(i))
            {
                if (j != 0)
                    j = array[j-1];
                else
                    i = i+1;
            }
        }
       
       //    System.out.println(" chec "+ans);
            return ans;
    }
      static void makearray(String patten, int patten_lenght, int array[])
    {
        int l = 0;
        int i = 1;
        array[0] = 0;  
        while (i < patten_lenght)
        {
            if (patten.charAt(i) == patten.charAt(l))
            {
                l++;
                array[i] = l;
                i++;
            }
            else  
            {
                if (l != 0)
                {
                    l = array[l-1];
                }
                else  
                {
                    array[i] = l;
                    i++;
                }
            }
        }
    }
    
    
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
                                                           // KMP match button
        String text=text2.getText();
        String pattern=pattern2.getText();                 
        int result=KMP( pattern,text);                     
        if(result!=-1)
            Output2.setText("Pattern Matched at index "+result);
        else
            Output2.setText("Pattern Not Matched !");
    }//GEN-LAST:event_btn2ActionPerformed

    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searching().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BF;
    private javax.swing.JLabel KMP;
    private javax.swing.JLabel Output1;
    private javax.swing.JLabel Output2;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton exit;
    private javax.swing.JTextField pattern1;
    private javax.swing.JTextField pattern2;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables


}
